name: Build Enzyme-JAX

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    name: Build - ${{ matrix.os }} - python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-latest
          # # `ubuntu-22.04-arm` is considered more stable than `ubuntu-24.04-arm`:
          # # <https://github.com/orgs/community/discussions/148648#discussioncomment-12099554>.
          # - ubuntu-22.04-arm
          - macOS-latest
        python:
          - '3.12'
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache ccache files
        uses: actions/cache@v4
        with:
          path: ${{ runner.workspace }}/.ccache
          key: build-ccache-${{ matrix.os }}-${{ matrix.python }}
          restore-keys: |
            build-ccache-${{ matrix.os }}-
            build-ccache-
      - name: Install packages on Ubuntu
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-gt update
          sudo apt-get install -y ccache
      - name: Install packages on macOS
        if: ${{ startsWith(matrix.os, 'macOS') }}
        run: |
          brew install ccache
      # Don't rely only on bazel cache
      - name: Prepare ccache
        shell: bash
        run: |
          BINDIR="${{ runner.workspace }}/.bin"
          CCACHE_DIR=${{ runner.workspace }}/.ccache
          mkdir -pv "${BINDIR}"
          mkdir -pv "${CCACHE_DIR}"
          for compiler in cc c++ gcc g++ clang clang++; do
              if which "${compiler}" &> /dev/null; then
                  # Copy instead of symlink:
                  # <https://github.com/ccache/ccache/discussions/1279#discussioncomment-5687710>.
                  cp -v $(which ccache) "${BINDIR}/${compiler}"
              fi
          done
          echo "CCACHE_DIR=${CCACHE_DIR}" >> "${GITHUB_ENV}"
          echo "PATH=${BINDIR}:${PATH}" >> "${GITHUB_ENV}"
      - name: Show compilers
        run: |
          for compiler in cc c++ gcc g++ clang clang++; do
              which ${compiler} || true
              ${compiler} --version || true
              echo "-----"
          done
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: bazel-contrib/setup-bazel@0.13.0
        name: Set up Bazel
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.python }}
          # Share repository cache between workflows.
          repository-cache: true
          bazelisk-version: 1.x
      - name: Build enzymexlamlir-opt
        run: |
          bazel build --color=yes //:enzymexlamlir-opt --test_output=errors --sandbox_writable_path=${CCACHE_DIR}
        env:
          HERMETIC_PYTHON_VERSION: ${{ matrix.python }}
      # - name: Build wheel
      #   run: |
      #     bazel build --color=yes :wheel --test_output=errors
      #   env:
      #     HERMETIC_PYTHON_VERSION: ${{ matrix.python }}
      # - name: Upload wheel
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Enzyme-JAX-Wheel-${{ matrix.os }}-${{ matrix.python }}
      #     path: "bazel-bin/*.whl"
      #     retention-days: 90
